logstash:
  image: logstash
  container_name: logstash-1
  net: "pubsub"
  tty: true
  environment:
    - ELASTIC_IP=${ELASTIC_IP}
  volumes:
    - ./logstash:/config-dir
  command: logstash -f /config-dir/logstash.conf

kibana:
  image: kibana
  container_name: kibana-1
  net: "pubsub"
  environment:
    - ELASTICSEARCH_URL=${ELASTIC_URI}
  ports:
    - "5601:5601"