rabbitmq:
  image: rabbitmq:3-management
  container_name: rabbitmq-1
  hostname: my-rabbit
  net: "pubsub"
  environment:
    - LOGSPOUT=ignore
  ports:
    - "5672:5672"
    - "15672:15672"

logstash:
  image: logstash
  container_name: logstash-1
  net: "pubsub"
  tty: true
  command: logstash -e 'input { udp { port => 5000 codec => json } } output { stdout { } }'

logspout:
  build: ./logspout
  container_name: logspout-1
  net: "pubsub"
  environment:
    - ROUTE_URIS=logstash://logstash-1:5000
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - "9001:80"