logstash:
  image: logstash
  container_name: logstash-1
  net: "pubsub"
  tty: true
  environment:
    - ELASTIC_IP=${ELASTIC_IP}
  volumes:
    - ./logstash:/config-dir
  command: logstash -f /config-dir/logstash.conf